### ISSUE TITLE
Could you add the ability to show random trees

### ISSUE THREAD

**Issue by rachelss** [wrightaprilm/treesiftr#4]
In the Shiny app I can see the parsimony score for the best tree. I'd love to be able to show students the parsimony score for other trees (they could be randomly generated). Just a possible feature to add in future.

**Comment by wrightaprilm** [comment]
I can and I have in the [most recent release](https://github.com/wrightaprilm/treesiftr/releases/tag/v0.2.0). Thanks so much for this suggestion!
